dist: bionic
language: go
go:
- 1.14.2
env:
  global:
  - LANG=C
  - LC_ALL=C
deploy:
  provider: releases
  api_key:
    secure: SOwnDeAEI79nORlM60jvICLKAa70AqEEEDwj0ibdKFXkCIfkvi8/OaPnM30r3W+sqlvSAyPgQuQHDdIrGGYHDLtWphVb7YprtKo4upGm6Xw7EqzUT40agZoQn+8eFFoMHWuXEQD9yQk0aILmQoard5CwlnUHbQUjT0MnlMAODbjLOWsU+4J+dHZKn0p1OuWl4aVMJ3ECqukxVp32nhEngII1QVyYPoOLZbi7VGwU6wYGXmzFbkL4apt9y08pbRtZu1SN43evBaujRh/76W8h+0qvAZ9yoEvMcyKbvqiI5gpo8VAN3XjLs79V/h1KWvIuuufRUMnSd0R/2TT+z+dd/Xao0bY2kreedLa64aXyhHYQDKCWVnhi6K3BmBQ6McI9CW/BGQucjmj3lBqtl/rapZtvGSBfz/alzHJxi3/qG34xXIm0pAPvJrSxLrsTVJNtPYb1wpX7HxxX1ifF9rnK74stnTMRyoAnuxfoInxA7poWzgk8pKCBqs1JnmjarH/0yGhWdbY8IsETYVM2KC2tCgq9D1I1U503xrKujqdoEAMSKsExVMFod6rZDXfhK891EW5gGbWPi/HI3Tc8ngCgxF/9e5DovhF/K35n+5wygOGe0IDtHJQKOO5XFxaBAi/VXzu97G8PGtkg2XNg5EfdUeIYLKuoQ9Rr5anoN7J4nTA=
  skip_cleanup: true
  file_glob: true
  file:
    - pwnagotchi-*.zip
    - pwnagotchi-*.sha256
  on:
    tags: true
    repo: dadav/pwnagotchi
branches:
  only:
  - "/^v[0-9]+\\.[0-9]+\\.[0-9]+[A-Za-z0-9]*$/"
cache:
  apt: true
before_script:
- sudo apt-get -y update || true
- sudo apt-get -y install qemu-system-arm qemu-user-static binfmt-support bmap-tools kpartx
- sudo update-binfmts --display
script:
- sudo make clean
- sudo -E env "PATH=$PATH" make install
- sudo make image -e PWN_HOSTNAME=pwnagotchi PWN_VERSION=$TRAVIS_TAG
