dist: bionic
language: go

go:
  - 1.x

env:
  global:
  - LANG=C
  - LC_ALL=C

before_cache:
- mountpoint -q $TRAVIS_BUILD_DIR/tmp/mnt && sudo umount -R $TRAVIS_BUILD_DIR/tmp/mnt
- sudo find $TRAVIS_BUILD_DIR/tmp/ -name '*.img' -delete

cache:
  apt: true
  directories:
  - tmp/

before_script:
  - wget https://download.qemu.org/qemu-4.1.0.tar.xz
  - tar xvJf qemu-4.1.0.tar.xz
  - cd qemu-4.1.0
  - ./configure --target-list=arm-softmmu
  - sudo make
  - sudo make install
  - cd $TRAVIS_BUILD_DIR
  - sudo apt-get -y update
  - sudo apt-get -y install qemu-user-static binfmt-support bmap-tools kpartx
  - sudo update-binfmts --display

script:
- sudo -E env "PATH=$PATH" make -e PWN_HOSTNAME="pwnagotchi" VERSION="$TRAVIS_TAG"

