dist: bionic
language: go
go:
- 1.x
env:
  global:
  - LANG=C
  - LC_ALL=C
cache:
  apt: true
before_script:
- wget https://download.qemu.org/qemu-4.1.0.tar.xz
- tar xvJf qemu-4.1.0.tar.xz
- cd qemu-4.1.0
- "./configure --target-list=arm-softmmu"
- make -j$(nproc)
- sudo make install
- cd $TRAVIS_BUILD_DIR
- sudo apt-get -y update || true
- sudo apt-get -y install qemu-user-static binfmt-support bmap-tools kpartx
- sudo update-binfmts --display
script:
- sudo make clean
- sudo -E env "PATH=$PATH" make install
- sudo make image -e PWN_HOSTNAME=pwnagotchi VERSION=$TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: kLcUr4fCRKagskYRNVNz9Y6KNmw/cAztc7prWcPG0cVDMkPXP/h4fT0BJfhPQlZURemI9bvoDsTneBCX03Qgls7ilpBXyo8Nl8XrgSU0P2Ka3Eyx8QbqwI5buidmo+u7LCBOP/uXSFhG6Qep+KjJcuI6BGOLTVWNzn40mB7lhSoc/u4W/RWav4LniwO5U8W+pMdB8eyb7cqiqYDSbj42M7P2O21tmJXURmSbC3XIG17mAgKuXpx1xpu71Og1DQYc4n0GsjMR1zTqQJNNCvbsrLj7XWNHVHccIjbcuZdcH5NXsj6y4VMc0YkUucpyD9NDZKXxIqx8/ryfCuySJVX8EfeTSt+QVrQWA5HxbabNyGvqxcsdXUbQbxh2HbSrf++JD6Ni0+RAbbuWKf8nG63nbV4VsjRdGPGDzmgKQ4TEd+kV8BYZoTCmj8QFuuViQu2QLaSk8JSPpwTCCaDYuz+zxEZZhf1XgR7T6trsl7TIJFkJom/EAvLAjln5y3cRXhKBjNUoAgyJUz4n1JAYHrNaFGB8cyrj7VGKPa2sWtAGkgxaP3LZ6rGwm2ZVnwhb+DYMsRfVzEf8sc4wXgLsWkNDNzWFa1vv6sFaBcdSHIQh45VrpylYQT1x/OYUGD9PCK1i6eSHk0lpJp+S+jVVA5Ci0tRW7I3R4SD+FiUGSirw4f4=
  skip_cleanup: true
  file_glob: true
  file: pwnagotchi-*.zip
  on:
    repo: dadav/pwnagotchi
    all_branches: true
